#ifndef DINGOO_PIE_APP_METADATA_H
#define DINGOO_PIE_APP_METADATA_H

// This header is shared by C++ sources and the Windows resource compiler.
// Keep it preprocessor-only; do not add C++ declarations here.
#define DINGOO_PIE_COMPANY_NAME "BL2CK"
#define DINGOO_PIE_FILE_DESCRIPTION "Dingoo Game Emulator"
#define DINGOO_PIE_PRODUCT_NAME "DingooPie"
#define DINGOO_PIE_INTERNAL_NAME "DingooPie"
#define DINGOO_PIE_ORIGINAL_FILENAME "DingooPie.exe"

#define DINGOO_PIE_VERSION_MAJOR 1
#define DINGOO_PIE_VERSION_MINOR 5
#define DINGOO_PIE_VERSION_PATCH 0
#define DINGOO_PIE_VERSION_BUILD 0
#define DINGOO_PIE_VERSION_TEXT "1.5"

#define DINGOO_PIE_WIDE_LITERAL2(value) L##value
#define DINGOO_PIE_WIDE_LITERAL(value) DINGOO_PIE_WIDE_LITERAL2(value)

#define DINGOO_PIE_FILE_DESCRIPTION_W DINGOO_PIE_WIDE_LITERAL(DINGOO_PIE_FILE_DESCRIPTION)
#define DINGOO_PIE_PRODUCT_NAME_W DINGOO_PIE_WIDE_LITERAL(DINGOO_PIE_PRODUCT_NAME)
#define DINGOO_PIE_VERSION_TEXT_W DINGOO_PIE_WIDE_LITERAL(DINGOO_PIE_VERSION_TEXT)

#endif
